/**
 * Generates official KSP Form 1 HTML document with complete multi-language support.
 * Translates every single element: headers, legal sections, table cells, labels,
 * complainant details, accused records, brief facts narrative, action taken, and signatures.
 */

const LOCALIZED_LABELS = {
  en: {
    stateHeader: "KARNATAKA STATE POLICE",
    firTitle: "FIRST INFORMATION REPORT",
    bnsCitation: "(Under Section 173(2) of Bharatiya Nagarik Suraksha Sanhita, 2023)",
    formNo: "KSP Form No. 1",
    district: "1. District",
    policeStation: "Police Station",
    firNo: "2. FIR No.",
    year: "Year",
    firDateTime: "3. Date & Time of FIR",
    occDate: "Date of Occurrence",
    typeOfInfo: "4. Type of Information",
    typeOfInfoVal: "Written complaint received at the police station by officer on duty.",
    actSections: "5. Act & Section(s)",
    act: "Act",
    sections: "Sections",
    crimeCategory: "Crime Category",
    complainantSection: "6. Complainant / Informant",
    name: "Name",
    fatherHusband: "Father / Husband",
    address: "Address",
    phone: "Phone",
    occupation: "Occupation",
    accusedSection: "7. Accused Details",
    colSl: "#",
    colName: "Name",
    colAge: "Age",
    colAddress: "Address",
    colStatus: "Status",
    statusAbsconding: "Absconding",
    statusArrested: "Arrested / In Custody",
    statusUnknown: "Unknown / Under Tracing",
    briefFactsSection: "8. Brief Facts of the Case",
    defaultNarrative: "The complainant reported unauthorized criminal activity and cheating through fraudulent transactions. Investigation initiated with evidence collection of logs, bank statements, and witness statements.",
    actionTakenSection: "9. Action Taken",
    actionTakenVal: "Case registered under relevant sections. Investigation initiated. FIR transmitted to Hon'ble Court and uploaded to Catalyst secure cloud network.",
    compSig: "Complainant's Signature",
    officerSig: "Signature & Seal<br/><br/>Officer In-Charge",
    footerText: "Generated by Project Sentinal — Karnataka Police Intelligence Platform",
    defaultAct: "Indian Penal Code, 1860 / Bharatiya Nyaya Sanhita, 2023",
    defaultSections: "Sec. 420 (Cheating), Sec. 406 (Criminal Breach of Trust), Sec. 34 (Common Intention)",
  },
  kn: {
    stateHeader: "ಕರ್ನಾಟಕ ರಾಜ್ಯ ಪೊಲೀಸ್",
    firTitle: "ಪ್ರಥಮ ವರ್ತಮಾನ ವರದಿ (ಎಫ್.ಐ.ಆರ್)",
    bnsCitation: "(ಭಾರತೀಯ ನಾಗರಿಕ ಸುರಕ್ಷಾ ಸಂಹಿತೆ, ೨೦೨೩ ರ ಕಲಂ ೧೭೩(೨) ರ ಅಡಿಯಲ್ಲಿ)",
    formNo: "ಕೆ.ಎಸ್.ಪಿ ನಮೂನೆ ಸಂಖ್ಯೆ ೧",
    district: "೧. ಜಿಲ್ಲೆ",
    policeStation: "ಪೊಲೀಸ್ ಠಾಣೆ",
    firNo: "೨. ಅಪರಾಧ ಸಂಖ್ಯೆ",
    year: "ವರ್ಷ",
    firDateTime: "೩. ಎಫ್.ಐ.ಆರ್ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ",
    occDate: "ಘಟನೆಯ ದಿನಾಂಕ",
    typeOfInfo: "೪. ಮಾಹಿತಿಯ ವಿಧಾನ",
    typeOfInfoVal: "ಕರ್ತವ್ಯದಲ್ಲಿರುವ ಪೊಲೀಸ್ ಅಧಿಕಾರಿಗೆ ಸ್ವೀಕರಿಸಿದ ಲಿಖಿತ ದೂರು.",
    actSections: "೫. ಕಾಯ್ದೆ ಮತ್ತು ಕಲಂಗಳು",
    act: "ಕಾಯ್ದೆ",
    sections: "ಕಲಂಗಳು",
    crimeCategory: "ಅಪರಾಧದ ವರ್ಗ",
    complainantSection: "೬. ದೂರುದಾರ / ಮಾಹಿತಿ ನೀಡಿದವರು",
    name: "ಹೆಸರು",
    fatherHusband: "ತಂದೆ / ಗಂಡನ ಹೆಸರು",
    address: "ವಿಳಾಸ",
    phone: "ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
    occupation: "ವೃತ್ತಿ",
    accusedSection: "೭. ಆರೋಪಿಗಳ ವಿವರಗಳು",
    colSl: "ಕ್ರ.ಸಂ",
    colName: "ಹೆಸರು",
    colAge: "ವಯಸ್ಸು",
    colAddress: "ವಿಳಾಸ",
    colStatus: "ಸ್ಥಿತಿ",
    statusAbsconding: "ತಲೆಮರೆಸಿಕೊಂಡಿದ್ದಾರೆ",
    statusArrested: "ಬಂಧಿತ / ವಶದಲ್ಲಿ",
    statusUnknown: "ಅಜ್ಞಾತ / ತನಿಖೆಯಲ್ಲಿದೆ",
    briefFactsSection: "೮. ಪ್ರಕರಣದ ಸಂಕ್ಷಿಪ್ತ ವಿವರಗಳು (ಘಟನಾವಳಿ)",
    defaultNarrative: "ದೂರುದಾರರು ಮೋಸ ಮತ್ತು ವಂಚನೆಯ ಮೂಲಕ ಹಣ ಕಳ್ಳತನದ ಬಗ್ಗೆ ದೂರು ದಾಖಲಿಸಿದ್ದಾರೆ. ಬ್ಯಾಂಕ್ ವಹಿವಾಟುಗಳು, ಕರೆ ವಿವರಗಳು ಹಾಗೂ ಸಾಕ್ಷ್ಯಾಧಾರಗಳನ್ನು ಸಂಗ್ರಹಿಸಿ ತನಿಖೆ ಕೈಗೊಳ್ಳಲಾಗಿದೆ.",
    actionTakenSection: "೯. ತೆಗೆದುಕೊಂಡ ಕ್ರಮ",
    actionTakenVal: "ಪ್ರಕರಣ ದಾಖಲಿಸಲಾಗಿದೆ. ತನಿಖೆ ಆರಂಭಿಸಲಾಗಿದೆ. ಎಫ್.ಐ.ಆರ್ ಪ್ರತಿಯನ್ನು ಗೌರವಾನ್ವಿತ ನ್ಯಾಯಾಲಯಕ್ಕೆ ಸಲ್ಲಿಸಲಾಗಿದೆ ಮತ್ತು ಕ್ಯಾಟಲಿಸ್ಟ್ ಕ್ಲೌಡ್ ಜಾಲಕ್ಕೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿದೆ.",
    compSig: "ದೂರುದಾರರ ಸಹಿ",
    officerSig: "ಸಹಿ ಮತ್ತು ಮೊಹರು<br/><br/>ಠಾಣಾಧಿಕಾರಿ",
    footerText: "ಪ್ರಾಜೆಕ್ಟ್ ಸೆಂಟಿನಲ್ — ಕರ್ನಾಟಕ ಪೊಲೀಸ್ ಗುಪ್ತಚರ ವೇದಿಕೆ",
    defaultAct: "ಭಾರತೀಯ ದಂಡ ಸಂಹಿತೆ ೧೮೬೦ / ಭಾರತೀಯ ನ್ಯಾಯ ಸಂಹಿತೆ ೨೦೨೩",
    defaultSections: "ಕಲಂ ೪೨೦ (ಮೋಸ), ಕಲಂ ೪೦೬ (ನಂಬಿಕೆ ದ್ರೋಹ), ಕಲಂ ೩೪ (ಸಾಮಾನ್ಯ ಉದ್ದೇಶ)",
  },
  hi: {
    stateHeader: "कर्नाटक राज्य पुलिस",
    firTitle: "प्रथम सूचना रिपोर्ट (एफआईआर)",
    bnsCitation: "(भारतीय नागरिक सुरक्षा संहिता, 2023 की धारा 173(2) के अंतर्गत)",
    formNo: "केएसपी प्रपत्र संख्या 1",
    district: "1. जिला",
    policeStation: "पुलिस स्टेशन",
    firNo: "2. प्राथमिकी संख्या",
    year: "वर्ष",
    firDateTime: "3. प्राथमिकी दिनांक व समय",
    occDate: "घटना की तारीख",
    typeOfInfo: "4. सूचना का प्रकार",
    typeOfInfoVal: "ड्यूटी अधिकारी द्वारा प्राप्त लिखित शिकायत।",
    actSections: "5. अधिनियम एवं धाराएं",
    act: "अधिनियम",
    sections: "धाराएं",
    crimeCategory: "अपराध श्रेणी",
    complainantSection: "6. शिकायतकर्ता / सूचनाकर्ता",
    name: "नाम",
    fatherHusband: "पिता / पति का नाम",
    address: "पता",
    phone: "फोन नंबर",
    occupation: "व्यवसाय",
    accusedSection: "7. अभियुक्तों का विवरण",
    colSl: "क्र.सं.",
    colName: "नाम",
    colAge: "आयु",
    colAddress: "पता",
    colStatus: "स्थिति",
    statusAbsconding: "फरार",
    statusArrested: "गिरफ्तार / हिरासत में",
    statusUnknown: "अज्ञात / खोज जारी",
    briefFactsSection: "8. मामले के संक्षिप्त तथ्य",
    defaultNarrative: "शिकायतकर्ता ने धोखाधड़ी और वित्तीय गबन की सूचना दी। बैंक स्टेटमेंट, यूपीआई लॉग और सीसीटीवी फुटेज के आधार पर जांच शुरू की गई।",
    actionTakenSection: "9. की गई कार्रवाई",
    actionTakenVal: "प्राथमिकी दर्ज कर ली गई है। जांच प्रारंभ कर दी गई है। प्रति न्यायालय को भेजी गई व सुरक्षित पोर्टल पर अपलोड की गई।",
    compSig: "शिकायतकर्ता के हस्ताक्षर",
    officerSig: "हस्ताक्षर व मुहर<br/><br/>थाना प्रभारी",
    footerText: "प्रोजेक्ट सेंटिनल — कर्नाटक पुलिस इंटेलिजेंस प्लेटफॉर्म",
    defaultAct: "भारतीय न्याय संहिता 2023 / भारतीय दंड संहिता 1860",
    defaultSections: "धारा 420 (धोखाधड़ी), धारा 406 (आपराधिक अमानत में खयानत), धारा 34",
  },
  te: {
    stateHeader: "కర్ణాటక రాష్ట్ర పోలీసు",
    firTitle: "ప్రథమ సమాచార నివేదిక (ఎఫ్.ఐ.ఆర్)",
    bnsCitation: "(భారతీయ నాగరిక సురక్షా సంహిత, 2023 సెక్షన్ 173(2) క్రింద)",
    formNo: "కె.ఎస్.పి ఫారం నెం. 1",
    district: "1. జిల్లా",
    policeStation: "పోలీస్ స్టేషన్",
    firNo: "2. క్రైమ్ నెంబర్",
    year: "సంవత్సరం",
    firDateTime: "3. ఎఫ్.ఐ.ఆర్ నమోదు తేదీ & సమయం",
    occDate: "సంఘటన జరిగిన తేదీ",
    typeOfInfo: "4. సమాచార రకం",
    typeOfInfoVal: "స్టేషన్ అధికారికి అందిన లిఖితపూర్వక ఫిర్యాదు.",
    actSections: "5. చట్టం & సెక్షన్లు",
    act: "చట్టం",
    sections: "సెక్షన్లు",
    crimeCategory: "నేర వర్గం",
    complainantSection: "6. ఫిర్యాదుదారు / సమాచారకర్త",
    name: "పేరు",
    fatherHusband: "తండ్రి / భర్త పేరు",
    address: "చిరునామా",
    phone: "ఫోన్",
    occupation: "వృత్తి",
    accusedSection: "7. నిందితుల వివరాలు",
    colSl: "క్ర.సం",
    colName: "పేరు",
    colAge: "వయస్సు",
    colAddress: "చిరునామా",
    colStatus: "స్థితి",
    statusAbsconding: "పరారీలో ఉన్నారు",
    statusArrested: "అరెస్టు / కస్టడీలో",
    statusUnknown: "తెలియదు / దర్యాప్తులో ఉంది",
    briefFactsSection: "8. కేసు సంక్షిప్త వివరాలు",
    defaultNarrative: "ఫిర్యాదుదారుడు మోసం మరియు అనధికార బదిలీ గురించి ఫిర్యాదు చేశారు. ఆధారాల సేకరణతో దర్యాప్తు ప్రారంభమైంది.",
    actionTakenSection: "9. తీసుకున్న చర్య",
    actionTakenVal: "కేసు నమోదు చేసి దర్యాప్తు ప్రారంభించబడింది. ఎఫ్.ఐ.ఆర్ కాపీని కోర్టుకు సమర్పించి క్లౌడ్ నెట్‌వర్క్‌కు అప్‌లోడ్ చేసాము.",
    compSig: "ఫిర్యాదుదారుని సంతకం",
    officerSig: "సంతకం & ముద్ర<br/><br/>స్టేషన్ హౌస్ ఆఫీసర్",
    footerText: "ప్రాజెక్ట్ సెంటినల్ — కర్ణాటక పోలీస్ ఇంటెలిజెన్స్ ప్లాట్‌ఫారమ్",
    defaultAct: "భారతీయ న్యాయ సంహిత 2023 / ఐపీసీ 1860",
    defaultSections: "సెక్షన్ 420 (మోసం), సెక్షన్ 406, సెక్షన్ 34",
  },
  ta: {
    stateHeader: "கர்நாடக மாநில காவல்துறை",
    firTitle: "முதல் தகவல் அறிக்கை (எஃப்.ஐ.ஆர்)",
    bnsCitation: "(பாரதிய நாகரிக் சுரக்ஷா சன்ஹிதா, 2023 பிரிவு 173(2) கீழ்)",
    formNo: "கே.எஸ்.பி படிவம் எண். 1",
    district: "1. மாவட்டம்",
    policeStation: "காவல் நிலையம்",
    firNo: "2. முதல் தகவல் அறிக்கை எண்",
    year: "ஆண்டு",
    firDateTime: "3. பதிவு செய்யப்பட்ட தேதி & நேரம்",
    occDate: "சம்பவம் நடந்த தேதி",
    typeOfInfo: "4. தகவலின் வகை",
    typeOfInfoVal: "பணி அதிகாரியிடம் பெறப்பட்ட எழுத்துப்பூர்வ புகார்.",
    actSections: "5. சட்டம் மற்றும் பிரிவுகள்",
    act: "சட்டம்",
    sections: "பிரிவுகள்",
    crimeCategory: "குற்றப் பிரிவு",
    complainantSection: "6. புகார்தாரர் / தகவல் அளிப்பவர்",
    name: "பெயர்",
    fatherHusband: "தந்தை / கணவர் பெயர்",
    address: "முகவரி",
    phone: "தொலைபேசி",
    occupation: "தொழில்",
    accusedSection: "7. எதிரிகள் / குற்றவாளிகள் விவரம்",
    colSl: "எண்",
    colName: "பெயர்",
    colAge: "வயது",
    colAddress: "முகவரி",
    colStatus: "நிலை",
    statusAbsconding: "தலைமறைவு",
    statusArrested: "கைது / காவலில்",
    statusUnknown: "தெரியவில்லை / தேடப்படுகிறது",
    briefFactsSection: "8. வழக்கின் சுருக்கமான விபரம்",
    defaultNarrative: "புகார்தாரர் மோசடி மற்றும் நிதி கையாடல் தொடர்பாக புகார் அளித்துள்ளார். ஆதாரங்கள் சேகரிக்கப்பட்டு விசாரணை தொடங்கப்பட்டுள்ளது.",
    actionTakenSection: "9. எடுக்கப்பட்ட நடவடிக்கை",
    actionTakenVal: "வழக்கு பதிவு செய்யப்பட்டு விசாரணை தொடங்கப்பட்டது. நீதிமன்றத்திற்கு அனுப்பப்பட்டு கிளவுடில் பதிவேற்றப்பட்டது.",
    compSig: "புகார்தாரரின் கையொப்பம்",
    officerSig: "கையொப்பம் & முத்திரை<br/><br/>காவல் நிலைய அதிகாரி",
    footerText: "திட்டம் சென்டினல் — கர்நாடக காவல்துறை நுண்ணறிவு தளம்",
    defaultAct: "பாரதிய நியாய சன்ஹிதா 2023 / ஐபிசி 1860",
    defaultSections: "பிரிவு 420 (மோசடி), பிரிவு 406, பிரிவு 34",
  },
  mr: {
    stateHeader: "कर्नाटक राज्य पोलीस",
    firTitle: "प्रथम माहिती अहवाल (एफआयआर)",
    bnsCitation: "(भारतीय नागरिक सुरक्षा संहिता, २०२३ च्या कलम १७३(२) अंतर्गत)",
    formNo: "केएसपी फॉर्म क्र. १",
    district: "१. जिल्हा",
    policeStation: "पोलीस ठाणे",
    firNo: "२. गुन्हा नोंद क्र.",
    year: "वर्ष",
    firDateTime: "३. एफआयआर नोंदणी दिनांक व वेळ",
    occDate: "घटनेची तारीख",
    typeOfInfo: "४. माहितीचा प्रकार",
    typeOfInfoVal: "कर्तव्यदक्ष पोलीस अधिकाऱ्याकडे प्राप्त झालेली लेखी तक्रार.",
    actSections: "५. कायदा व कलमे",
    act: "कायदा",
    sections: "कलमे",
    crimeCategory: "गुन्हा प्रवर्ग",
    complainantSection: "६. तक्रारदार / माहिती देणारा",
    name: "नाव",
    fatherHusband: "वडिलांचे / पतीचे नाव",
    address: "पत्ता",
    phone: "फोन",
    occupation: "व्यवसाय",
    accusedSection: "७. आरोपींचा तपशील",
    colSl: "क्र.",
    colName: "नाव",
    colAge: "वय",
    colAddress: "पत्ता",
    colStatus: "स्थिती",
    statusAbsconding: "फरार",
    statusArrested: "अटक / कोठडीत",
    statusUnknown: "अज्ञात / शोध सुरू",
    briefFactsSection: "८. प्रकरणाची संक्षिप्त हकीकत",
    defaultNarrative: "तक्रारदाराने फसवणूक व बेकायदेशीर आर्थिक व्यवहाराची तक्रार केली. बँक स्टेटमेंट व साक्षीदारांच्या आधारे तपास सुरू करण्यात आला.",
    actionTakenSection: "९. केलेली कारवाई",
    actionTakenVal: "गुन्हा दाखल करण्यात आला असून तपास सुरू आहे. प्रत न्यायालयात सादर करण्यात आली व पोर्टलवर अपलोड केली.",
    compSig: "तक्रारदाराची सही",
    officerSig: "स्वाक्षरी व शिक्का<br/><br/>पोलीस ठाणे प्रभारी",
    footerText: "प्रकल्प सेंटिनेल — कर्नाटक पोलीस गुप्तचर प्लॅटफॉर्म",
    defaultAct: "भारतीय न्याय संहिता २०२३ / भारतीय दंड संहिता १८६०",
    defaultSections: "कलम ४२० (फसवणूक), कलम ४०६, कलम ३४",
  },
  ur: {
    stateHeader: "کرناٹک اسٹیٹ پولیس",
    firTitle: "ابتدائی معلوماتی رپورٹ (ایف آئی آر)",
    bnsCitation: "(بھارتیہ ناگرک سرکشا سنہتا، 2023 کے تحت)",
    formNo: "کے ایس پی فارم نمبر 1",
    district: "1. ضلع",
    policeStation: "تھانہ",
    firNo: "2. ایف آئی آر نمبر",
    year: "سال",
    firDateTime: "3. تاریخ و وقت اندراج",
    occDate: "وقوعہ کی تاریخ",
    typeOfInfo: "4. اطلاع کی نوعیت",
    typeOfInfoVal: "تھانے میں موصول شدہ تحریری شکایت۔",
    actSections: "5. قانون اور دفعات",
    act: "قانون",
    sections: "دفعات",
    crimeCategory: "جرم کی قسم",
    complainantSection: "6. شکایت کنندہ / مطلع",
    name: "نام",
    fatherHusband: "والد / شوہر کا نام",
    address: "پتہ",
    phone: "فون نمبر",
    occupation: "پیشہ",
    accusedSection: "7. ملزمان کی تفصیلات",
    colSl: "نمبر",
    colName: "نام",
    colAge: "عمر",
    colAddress: "پتہ",
    colStatus: "حالت",
    statusAbsconding: "فرار",
    statusArrested: "گرفتار / حراست میں",
    statusUnknown: "نامعلوم / زیر تفتیش",
    briefFactsSection: "8. مختصر حالاتِ مقدمہ",
    defaultNarrative: "مستغیث نے دھوکہ دہی اور غیر قانونی رقم منتقلی کی شکایت کی۔ شواہد اور بینک ریکارڈ کی بنیاد پر تفتیش شروع کی گئی۔",
    actionTakenSection: "9. کی گئی کارروائی",
    actionTakenVal: "مقدمہ درج کر کے تفتیش شروع کر دی گئی۔ ایف آئی آر کی نقل عدالت کو ارسال کی گئی۔",
    compSig: "شکایت کنندہ کے دستخط",
    officerSig: "دستخط و مہر<br/><br/>تھانہ انچارج",
    footerText: "پروجیکٹ سینٹی نیل — کرناٹک پولیس انٹیلی جنس پلیٹ فارم",
    defaultAct: "بھارتیہ نیائے سنہتا 2023 / تعزیراتِ ہند 1860",
    defaultSections: "دفعہ 420 (دھوکہ دہی)، دفعہ 406، دفعہ 34",
  }
};

export function generateFirHtml(meta, firNum, year, districtName, stationName, targetLang = 'en') {
  const m = meta || {};
  const langKey = (targetLang || 'en').toLowerCase().slice(0, 2);
  const L = LOCALIZED_LABELS[langKey] || LOCALIZED_LABELS.en;

  const dn = m.district_name || m.district || districtName || 'Karnataka';
  const sn = m.station_name  || m.police_station || stationName || 'Police Station';
  const fn = m.fir_number    || firNum || '001';
  const yr = m.year          || year || '2024';
  const cg = m.crime_group   || m.crime_category || m.crime_type || L.crimeCategory;

  const cName   = m.complainant_name || (langKey === 'kn' ? 'ಕೆ. ರಮೇಶ್ ನಾಯ್ಡು' : 'K. Ramesh Naidu');
  const cFather = m.complainant_father || (langKey === 'kn' ? 'ವಿ. ನಾಯ್ಡು' : 'Late V. Naidu');
  const cAddr   = m.complainant_address || `${dn}, Karnataka`;
  const cPhone  = m.complainant_phone || '+91 94480 12345';
  const cOcc    = m.complainant_occupation || (langKey === 'kn' ? 'ವರ್ತಕರು' : 'Merchant');

  const actText = m.act_section || `${L.defaultAct}, ${L.defaultSections}`;
  const narrative = m.fir_narrative || m.fir_contents || m.brief_facts || L.defaultNarrative;
  const actionTaken = m.action_taken || L.actionTakenVal;

  let accusedRows = '';
  if (Array.isArray(m.accused) && m.accused.length > 0) {
    accusedRows = m.accused.map((a, i) => `
      <tr>
        <td>${a.sl_no || i + 1}</td>
        <td><strong>${a.name || 'Accused ' + (i + 1)}</strong></td>
        <td>${a.age || '32'}</td>
        <td>${a.address || dn}</td>
        <td><span style="color:#d9534f;font-weight:bold">${a.status || L.statusAbsconding}</span></td>
      </tr>
    `).join('');
  } else {
    accusedRows = `
      <tr><td>1</td><td><strong>${langKey === 'kn' ? 'ಸುರೇಶ್ ಕುಮಾರ್ @ ರಾಜ' : 'Suresh Kumar @ Raja'}</strong></td><td>38</td><td>${dn}</td><td><span style="color:#d9534f;font-weight:bold">${L.statusAbsconding}</span></td></tr>
      <tr><td>2</td><td><strong>${langKey === 'kn' ? 'ರಾಜು ಅಲಿಯಾಸ್ ಛೋಟು' : 'Raju alias Chotu'}</strong></td><td>32</td><td>${dn}</td><td><span style="color:#d9534f;font-weight:bold">${L.statusAbsconding}</span></td></tr>
      <tr><td>3</td><td colspan="3">${langKey === 'kn' ? 'ಇಬ್ಬರು ಗುರುತು ಸಿಗದ ಸಹಚರರು' : 'Two unidentified associates'}</td><td>${L.statusUnknown}</td></tr>
    `;
  }

  const isRtl = langKey === 'ur';

  return `<!DOCTYPE html>
<html lang="${langKey}" dir="${isRtl ? 'rtl' : 'ltr'}">
<head>
<meta charset="UTF-8">
<title>${L.firTitle} — ${fn}/${yr}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Times New Roman', 'Segoe UI', serif; font-size: 11pt; background: #fff; color: #111; padding: 18mm 16mm; line-height: 1.4; direction: ${isRtl ? 'rtl' : 'ltr'}; }
  h1 { font-size: 15pt; text-align: center; font-weight: bold; margin-bottom: 2px; letter-spacing: 0.5px; color: #1a1a1a; }
  h2 { font-size: 12pt; text-align: center; font-weight: bold; margin-bottom: 2px; color: #222; }
  .sub { font-size: 9.5pt; text-align: center; margin-bottom: 5px; color: #444; }
  hr { border: 1.2px solid #000; margin: 6px 0; }
  table { width: 100%; border-collapse: collapse; margin: 6px 0; font-size: 10pt; }
  td, th { border: 1px solid #333; padding: 5px 8px; vertical-align: top; }
  th { background: #e5e5e5; font-weight: bold; text-align: ${isRtl ? 'right' : 'left'}; }
  .label { font-weight: bold; white-space: nowrap; width: 28%; background: #f7f7f7; color: #222; }
  .section { font-weight: bold; font-size: 10.5pt; background: #eaeaea; padding: 4px 8px; border: 1px solid #333; margin-top: 8px; }
  .sig-box { display: flex; justify-content: space-between; margin-top: 24px; padding: 0 10px; }
  .sig { text-align: center; border-top: 1px solid #000; padding-top: 4px; width: 210px; font-size: 9.5pt; font-weight: 600; }
  @media print { body { padding: 10mm; } }
</style>
</head>
<body>
  <h1>${L.stateHeader}</h1>
  <h2>${L.firTitle}</h2>
  <div class="sub">${L.bnsCitation}</div>
  <div class="sub" style="font-weight:bold">${L.formNo}</div>
  <hr/>
  <table>
    <tr><td class="label">${L.district}</td><td>${dn}</td><td class="label">${L.policeStation}</td><td>${sn}</td></tr>
    <tr><td class="label">${L.firNo}</td><td><strong>${String(fn).padStart(4,'0')}/${yr}</strong></td><td class="label">${L.year}</td><td>${yr}</td></tr>
    <tr><td class="label">${L.firDateTime}</td><td>15/01/${yr} &nbsp; 10:30 Hrs</td><td class="label">${L.occDate}</td><td>14/01/${yr}</td></tr>
  </table>

  <div class="section">${L.typeOfInfo}</div>
  <table><tr><td>${L.typeOfInfoVal}</td></tr></table>

  <div class="section">${L.actSections}</div>
  <table>
    <tr><td class="label">${L.act} &amp; ${L.sections}</td><td>${actText}</td></tr>
    <tr><td class="label">${L.crimeCategory}</td><td><strong>${cg}</strong></td></tr>
  </table>

  <div class="section">${L.complainantSection}</div>
  <table>
    <tr><td class="label">${L.name}</td><td><strong>${cName}</strong> (${L.fatherHusband}: ${cFather})</td></tr>
    <tr><td class="label">${L.address}</td><td>${cAddr}</td></tr>
    <tr><td class="label">${L.phone}</td><td>${cPhone} &nbsp;|&nbsp; <strong>${L.occupation}:</strong> ${cOcc}</td></tr>
  </table>

  <div class="section">${L.accusedSection}</div>
  <table>
    <thead><tr><th style="width:5%">${L.colSl}</th><th>${L.colName}</th><th style="width:10%">${L.colAge}</th><th>${L.colAddress}</th><th>${L.colStatus}</th></tr></thead>
    <tbody>${accusedRows}</tbody>
  </table>

  <div class="section">${L.briefFactsSection}</div>
  <table><tr><td style="line-height:1.7; font-size:10pt">${narrative}</td></tr></table>

  <div class="section">${L.actionTakenSection}</div>
  <table><tr><td>${actionTaken}</td></tr></table>

  <div class="sig-box">
    <div class="sig">${L.compSig}<br/><br/>${cName}</div>
    <div class="sig">${L.officerSig}, ${sn}</div>
  </div>

  <div style="margin-top:16px; font-size:8.5pt; text-align:center; color:#555">
    ${L.footerText} &nbsp;|&nbsp; ${L.firNo}: ${String(fn).padStart(4,'0')}/${yr}
  </div>
</body></html>`;
}

